board/urls.py
from django.urls import path
from . import views

#게시판 API post
app_name = 'board'

urlpatterns = [
     #게시판
     path('', views.post_list, name='post_list'),                                  #게시판 전체 조회
     path('<int:category>', views.category_post_list, name='category_post_list'),  #게시판 카테고리 조회
     path('create_page/', views.create_page, name='create_page'),                  #게시글 작성 페이지 이동 
     path('post_detail/<int:post_id>', views.post_detail, name='post_detail'),     #게시글 상세 조회
     path('create/', views.post_create, name='post_create'),                       #게시글 작성
     path('delete/<int:post_id>', views.post_delete, name="post_delete"),          #게시글 삭제 
     path('update_page/<int:post_id>', views.update_page, name="update_page"),     #게시물 update 페이지 이동 
     path('update/<int:post_id>/', views.update, name='update'),                  #게시물 update

     #댓글 
     path('comment_create/<int:post_id>', views.comment_create, name="comment_create"),
     path('comment_delete/<int:comment_id>', views.comment_delete, name="comment_delete"),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views




app_name = "common"

urlpatterns = [
    path("", views.HomeView.as_view(), name="main"),
    path('login/', views.CustomLoginView.as_view(template_name="account/login.html"), name="login"),
    #path("login/", auth_views.LoginView.as_view(template_name="account/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.signup, name="signup")
]

# from .views import (
#     login_view,
#     logout_view,
#     signup_view,
# )

# app_name = 'account'
# urlpatterns = [
#     path('auth/', login_view, name='login'),
#     path('auth/expiration/', logout_view, name='logout'),
#     path('auth/new/', signup_view, name='signup'),
# ]

heco/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import BaseView, IndexView
from django.urls import path
from django.conf.urls import include
from heco import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path("", include("common.urls")),
    path('board/', include('board.urls')),
    path('chatbot/', include('gptChatBot.urls')),
    path('search/', include('search.urls')),
]

# urlpatterns = [
#     path("admin/", admin.site.urls),
#     path('base/', BaseView.as_view(), name='base'),
#     path('index/', IndexView.as_view(), name='index'),
#     path('board/', include('board.urls')),
#     path('account/', include('account.urls')),
# ]

board/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.IntegerChoices):
    DIET = 1
    BEGINNER = 2
    INTERMEDIATE = 3
    ADVANCED = 4


class Posts(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100)
    contents = models.CharField(max_length=2000)
    image_url = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    category = models.IntegerField(choices=Category.choices)
    user_id = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        db_column="user_id",
    )


class Comments(models.Model):
    id = models.AutoField(primary_key=True)
    contents = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    user_id = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        db_column="user_id",
    )
    post_id = models.ForeignKey(
        "Posts",
        on_delete=models.CASCADE,
        db_column="post_id",
    )

board/forms.py
from django import forms
from .models import Posts

class PostsForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = ('category', 'title', 'contents', 'image_url')

board/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from board.models import Category, Posts, Comments

import boto3
from botocore.exceptions import NoCredentialsError
import json

from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
import os
import requests
import openai

from django.core.paginator import Paginator

#게시글 전체 조회
def post_list(request):
    #user = User()
    #로그인 후 받아오는 방법 고민
    user_id = request.session.get('user_id')
    user_username =request.session.get('username')
    posts = Posts.objects.all()

    paginator = Paginator(posts, 9)  # 한 페이지에 9개
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'id' : user_id,
        'username' : user_username,
        }
    return render(request, 'board/post_list.html', context)


#게시글 카테고리 조회
def category_post_list(request, category):
    errMessage = {"err" : '게기글 조회 오류 발생으로 다시 조회 부탁드립니다.'}
    if request.method == 'GET':
        posts = Posts.objects.filter(category=category)
        id = request.GET.get('id')
        username = request.GET.get('username')

        paginator = Paginator(posts, 9)  # 한 페이지에 9개
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
            'page_obj': page_obj,
            'category': category,
            'id' : id,
            'username' : username,
            } 
        return render(request, 'board/category_post_list.html', context)
    return render(request, 'board/category_post_list.html', errMessage)


#게시글 상세 조회[게시글 username 가져와야함] 
def post_detail(request, post_id):
    #로그인 한 user
    id = request.GET.get('id')
    username = request.GET.get('username')
    #게시물 데이터
    post = get_object_or_404(Posts, id=post_id)
    #댓글 데이터
    comments = Comments.objects.filter(post_id=post_id)

    context = {
        'post': post,
        'comments' : comments,
        'id'  : id, 
        'username' : username,
    }
    return render(request, 'board/post_detail.html', context)

#게시글 작성 페이지 이동
def create_page(request):
    id = request.GET.get('id')
    username = request.GET.get('username')
    context = {
        'id' : id, 
        'username' : username,
    }
    return render(request, 'board/post_create.html', context)


#게시글 작성
def post_create(request):
    if request.method == 'POST':
        #게시판
        post = Posts()
        post.title = request.POST['title']
        post.contents = request.POST['contents']
        post.image_url = upload_to_aws(request.FILES['image']) #AWS S3 연결 
        post.category = request.POST['category']
        #user 데이터 가져올수 있는지 확인
        user = User.objects.get(id=request.POST['id'])
        post.user_id = user
        #저장(insert)
        post.save()
        
        #전체 게시글로 이동 
        #posts = Posts.objects.all()

        #context = {
        #    "posts": posts,
        #    "id" : request.POST['id'],
        #    "username" : request.POST['username']
        #}

        #글쓰기 성공시 이동 
        return redirect('board:post_list')
        #return render(request, 'board/post_list.html', context)  
    
    #글쓰기 실패시 이동
    return render(request, 'board/post_create.html', { })    



#게시글 수정 페이지 이동 
def update_page(request, post_id):
    post = get_object_or_404(Posts, id=post_id)    
    context = {
        'post' : post,
        'id' : request.GET.get('id'),
        'username' : request.GET.get('username'),
        }
    return render(request, 'board/post_update.html', context)

#게시글 수정
def update(request, post_id):
    post = Posts.objects.get(id=post_id)
    post.title = request.POST.get('title')
    post.contents = request.POST.get('contents')
    post.image_url = upload_to_aws(request.FILES['image']) #AWS S3 연결 
    # post.category = request.POST.get('category') #수정불가
    post.save()
    post = get_object_or_404(Posts, id=post_id)
    comments = Comments.objects.filter(post_id=post_id)
    context = {
        'post' : post,
        'comments' : comments,
        'id' : request.GET.get('id'),
        'username' : request.GET.get('username'),
        }
    return render(request, 'board/post_detail.html', context)
    

#게시글 삭제
def post_delete(request, post_id):
    post = get_object_or_404(Posts, id=post_id)
    post.delete()
    #posts = Posts.objects.all()
    #context = {
    #    'posts' : posts,
    #    'id' : request.GET.get('id'),
    #    'username' : request.GET.get('username')
    #}
    return redirect('board:post_list')
    #return render(request, 'board/post_list.html', context)
    
#댓글 생성 
def comment_create(request, post_id):
    #게시판 외래키, User 외래키 입력 
    post = Posts.objects.get(id=post_id)
    comment = Comments()
    comment.contents = request.POST['comment_content']
    user_id = request.POST.get('id')
    user_data = User.objects.get(id=user_id)  # id를 사용하여 UserData 인스턴스를 가져옴
    comment.user_id = user_data # 가져온 인스턴스를 할당
    comment.post_id = post
    #댓글 저장 
    comment.save()
    #댓글 조회
    comments = Comments.objects.filter(post_id=post_id)

    #댓글 저장 -> 게시판 상세 조회(게시글 데이터, 댓글 데이터)
    context = {
        'post':post,
        'comments' : comments,
        'id': request.GET.get('id'),
        'username': request.GET.get('username'),
    }

    return render(request, 'board/post_detail.html', context)


#댓글 삭제 
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comments, id=comment_id)
    comment.delete()
    
    post_id = request.GET.get('post_id')
    post = get_object_or_404(Posts, id=post_id)
    comments = Comments.objects.filter(post_id=post_id)

    context = {
        'post' : post,
        'comments' : comments,
        'id': request.GET.get('id'),
        'username': request.GET.get('username'),
    }
    return render(request, 'board/post_detail.html', context)

board/templates/board/main.html
{% extends 'index.html' %}

{% block content %}

<div>Board main.html</div>
<h1>게시판 페이지 </h1>

<!-- 게시판 카테고리 -->
<form method="GET" action="{% url 'post:select_list' %}">
    {% csrf_token %}
    <button name="category" value="1">식단</button>    
    <button name="category" value="2">초급자</button>    
    <button name="category" value="3">중급자</button>    
    <button name="category" value="4">고급자</button>    
</form>

<!-- 게시판 글 작성 페이지 이동 (로그인시에만) -->
{% if username %}
<form method="GET" action="{% url 'post:insert_page' %}">
    {% csrf_token %}
    <input type="hidden"  name="id" value="{{ id }}">
    <input type="hidden"  name="username" value="{{ username }}">
    <input type="submit"  value="글작성">
</form>
{% else %}
<input type="hidden" value="글작성">
{% endif %}

<table>
{% for list in postlist%}
    <ul>
        <li>
            <a href="{% url 'post:select_detail' list.id %}?id={{ id }}&username={{ username }}">
                {{ list.title }}
                <br>
                {{ list.contents }}
            </a>
        </li>
    </ul>
{% endfor %}
</table>


{% endblock %}

board/templates/board/post_detail.html
{% extends 'base.html' %}
{% block page_title %}
<title>게시글 상세보기</title>
{% endblock page_title %}

{% block content %}
<br><br><br>
<!-- 이전 페이지 버튼 -->
<div class="container mt-5 d-md-flex justify-content-md-start mb-3">
    <div class="shadow-sm mt-4 ">
      <button type="button" class="shadow-sm btn btn-outline-primary" onclick="goBack()">이전 페이지로 돌아가기</button>
    </div>
</div>
<!-- main -->
<div class="container mx-auto mt-5">
    <div class=" row card mb-4 shadow-sm border border-dark-subtle bg-body-tertiary bg-light">   
        <div class="card-body">
        <img src="{{ post.image_url }}" class="card-img-top img-fluid" style="max-width: 50%;" alt="...">
        <h5 class="card-title">{{ post.title }}</h5>
        <p>Author: {{ post.user_id.username }}</p>
        <p class="card-text">{{ post.contents }}</p>
        <p class="card-text"><small class="text-body-secondary">Created at: {{ post.created_at }}</small></p>
        </div>
    </div>
    <!-- 사용자는 댓글등록 버튼 출력 -->
    <div class="row card mb-3  shadow-sm border border-dark-subtle bg-body-tertiary bg-light">
        <h5>댓글</h5>
        <hr>
        {% for comment in comments %}
            {% if comment.user_id.username == request.session.username %}
                <div style="position: relative; display: inline-block;">
                    <a id="comment_delete" onclick="return deleteClick()" style="position: absolute; top: 0px; right: 10px;" href="{% url 'board:comment_delete' comment_id=comment.id %}?id={{ id }}&username={{ username }}&post_id={{ post.id }}">삭제</a>
                </div>
            {% endif %}
            <p>by. {{ comment.user_id.username }}</p>
            <p>{{ comment.contents }}</p>
            <p><small class="text-body-secondary">Created at: {{ comment.created_at }}</small></p>
            <hr>
        {% endfor %}
        
        {% if request.session.username %}
            <form method="POST" action="{% url 'board:comment_create' post_id=post.id %}?id={{ id }}&username={{ username }}">
                {% csrf_token %}
                <div id="comments" class="card-body">
                    <textarea class="form-control ms-3" id="comment_content" name="comment_content" rows="3" required></textarea>
                    <!-- for문  -->
                    <input type="hidden" name="id" value="{{ id }}">
                    <input type="hidden" name="username" value="{{ username }}">
                </div>
                <div style="text-align:right; margin-top:10px;">
                    <button type="submit" class="btn btn-outline-primary">댓글 저장</button>
                </div>
            </form>
        {% endif %}
                
    </div>

    <!-- 게시글 작성자는 수정하기 삭제하기버튼 활성화 -->
    {% if post.user_id.username == request.session.username %}
    <div class="row container d-md-flex justify-content-md-center mt-5 mb-3">
        <div class="col col-sm-2">
            <a id="post_update" href="{% url 'board:update_page' post_id=post.id %}?id={{ id }}&username={{ username }}" class="btn btn-outline-success">수정하기</a>    
        </div>
        <div class="col col-sm-2">
            <a id="post_delete" onclick="return deleteClick()" href="{% url 'board:post_delete' post_id=post.id %}?id={{ id }}&username={{ username }}"   class="btn btn-outline-danger">삭제하기</a>
        </div>
    </div>
    {% endif %}
</div>


<script>
    var comment_boolean = true; 

    function deleteClick(){
        if(confirm('삭제하시겠습니까?')){
            return true;
        } else {
            return false;
        }
    }
    
    //댓글 한번만 작성 하도록 
    function addInput(){
    
    }


</script>
<!-- 뒤로가기 -->
<script>
    function goBack() {
      window.history.back();
    }
</script>
{% endblock content %}

board/templates/board/post_list.html
{% extends 'base.html' %}

{% block page_title %}
<title>HECO-BOARD</title>
{% endblock page_title %}

{% block navbar %}
<!-- 게시판 안내 글자 -->
<div class="container d-md-flex mt-2 fw-medium">
  <ul class="nav nav-tabs mb-2">
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'board:post_list' %}">전체게시판</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'board:category_post_list' 1 %}?id={{ id }}&username={{ username }}">식단</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'board:category_post_list' 2%}?id={{ id }}&username={{ username }}">운동 - 초급</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'board:category_post_list' 3 %}?id={{ id }}&username={{ username }}">운동 중급</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'board:category_post_list' 4 %}?id={{ id }}&username={{ username }}">운동 고급</a>
    </li>
  </ul>
  <p>ID:
    {{ request.session.user_id }}
    Username:
    {{ request.session.username }}</p>
</div>
{% endblock navbar %}

{% block content %}
<br><br><br><br><br>
<!-- 이전 페이지 버튼 -->
<div class="container mt-5 d-md-flex justify-content-md-start mb-3">
  <div class="shadow-sm mt-4 ">
    <button type="button" class="shadow-sm btn btn-outline-primary" onclick="goBack()">이전 페이지로 돌아가기</button>
  </div>
</div>

<!-- main -->
<div class="container row mx-auto">
  <!-- col-sm-9, bmi, 게시글 -->
  <div class="container col-sm-9">
      <div class="container mx-auto mt-3 row-cols-1 mb-4">
        <div class="shadow-sm border border-dark-subtle bg-body-tertiary bg-light rounded-3">
          <p class="fw-medium fs-5 pt-2 text-body-primary text-center ">BMI 계산</p>
            <!-- 입력 폼 -->
            <form class="row mx-3" onsubmit="return calculateResult(event)">
              <div class="col-md-3">
                <label for="inputGender" class="form-label">성별</label>
                <select id="inputGender" class="form-select">
                  <option selected="selected" id="M">남</option>
                  <option id="FM">여</option>
                </select>
              </div>
              <div class="col-md-3">
                <label for="inputAge" class="form-label">나이</label>
                <input type="text" class="form-control" id="inputAge">
              </div>
              <div class="col-md-3">
                <label for="inputHeight" class="form-label">키(cm)</label>
                <input type="text" class="form-control" id="inputHeight">
              </div>
              <div class="col-md-3">
                <label for="inputWeight" class="form-label">몸무게(kg)</label>
                <input type="text" class="form-control" id="inputWeight">
              </div>
              <div class="d-md-flex justify-content-md-end mt-2">
                <button type="submit" class="btn btn-primary ">조회하기</button>
              </div>
            </form>
            <!-- 결과 출력 -->
            <div class="row mx-5">
              <label for="customRange1" class="form-label text-center">
                <p class="text-center mt-3">결과 - 당신의 BMI 지수는 <span id="result">{{ bmi }}</span>
                  <span id="resultText">{{ resultText }}</span>입니다.
                </p>
              </label>
              <input type="range" class="form-range mb-2" id="customRange1" min="10" max="48" step="1" value="{{ result }}">
              <div class="row mb-3 shadow-sm">
                <div class="col bg-success text-center pb-2">저체중</div>
                <div class="col bg-success bg-opacity-50 text-center pb-2">정상</div>
                <div class="col bg-success bg-opacity-10 text-center pb-2">과체중</div>
                <div class="col bg-warning-subtle text-center pb-2">비만</div>
                <div class="col bg-warning text-center pb-2">고도비만</div>
              </div>
            </div>
        </div>
      </div>
      <!-- 작성하기 버튼, 게시글 -->
      <div class="container mx-auto mt-3 row" id="post-container">
        <div class="col">
          <!-- 작성하기 -->
          {% if request.session.username %}
            <!-- 회원 -->
            <div class="d-grid shadow-sm gap-2 mb-4">
              <a href="{% url 'board:create_page' %}?id={{ id }}&username={{ username }}" class="btn btn-outline-primary">게시글 작성하기</a>
            </div>
          {% else %}
            <!-- 비회원 -->
            <div class="d-grid shadow-sm gap-2 mb-4">
              <button type="button" class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#exampleModal">게시글 작성하기</button>
            </div>
            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-body">
                    로그인 후 이용가능합니다.
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <a href="{% url 'common:login' %}" class="btn btn-primary">로그인하러가기</a>
                  </div>
                </div>
              </div>
            </div>
          {% endif %}
          <!-- 게시글 출력 -->
          <div id="post-list-container" class="row row-cols-1 row-cols-md-3 g-2 mb-5">
            <!-- page_obg 는 posts 에서 9개씩 얻어옴 -->
            {% for post in page_obj %}
              <div class="col">
                <div class="card h-100 shadow-sm">
                  <a href="{% url 'board:post_detail' post_id=post.id %}?id={{ id }}&username={{ username }}" class="text-decoration-none text-body">
                    <div class="row">
                      <div class="col">
                        <div class="image-section" style="padding-bottom: 55%; position: relative;">
                          <img src="{{ post.image_url }}" class="card-img-top" alt="" style="position: absolute; width: 100%; height: 100%;">
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col">
                        <div class="card-body body-section" style="height: 40%;">
                          <p class="text-body-secondary">카테고리: {{ post.get_category_display }}</p>
                          <h5 class="card-title">{{ post.title }}</h5>
                          <p class="card-text">{{ post.contents }}</p>
                          <p class="card-text"><small class="text-body-secondary">{{ post.created_at }}</small></p>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col">
                        <div class="card-footer footer-section" style="height: 10%;">
                          <small class="card-text">by. {{ post.user_id.username }}</small>
                        </div>
                      </div>
                    </div>
                  </a>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
      <div class="pagination d-md-flex justify-content-md-center g-2 ">
        {% if page_obj.has_previous %}
          <a href="?page=1" class="btn btn-outline-primary me-2">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-primary me-2">previous</a>
        {% endif %}
  
        {% for num in page_obj.paginator.page_range %}
          {% if page_obj.number == num %}
            <a href="?page={{ num }}" class="btn btn-primary me-2 ">{{ num }}</a>
          {% else %}
            <a href="?page={{ num }}" class="btn btn-outline-primary me-2">{{ num }}</a>
          {% endif %}
        {% endfor %}
  
        {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-primary me-2">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-outline-primary me-2">last &raquo;</a>
        {% endif %}
      </div>
  </div>
  <!-- 오른쪽(식단 추천) -->
  <div class="col-sm-3 order-lg-2 card h-100 mt-3 shadow-sm border border-dark-subtle bg-body-tertiary bg-light rounded-3">
    <p class="text-center pt-2 mt-2">식단</p><hr>
    <!-- 아침, 점심, 저녁 체크 -->
    <fieldset class="row mb-3 input-group">
      <legend class="col-form-label col-sm-3 pt-0">식사</legend>
        <div class="form-check col-sm-3">
          <input class="form-check-input" type="radio" name="gridRadios" id="meal1" value="breakfast" checked>
          <label class="form-check-label" for="meal1">
            아침
          </label>
        </div>
        <div class="form-check col-sm-3">
          <input class="form-check-input" type="radio" name="gridRadios" id="meal2" value="lunch">
          <label class="form-check-label" for="meal2">
            점심
          </label>
        </div>
        <div class="form-check col-sm-3">
          <input class="form-check-input" type="radio" name="gridRadios" id="meal3" value="dinner">
          <label class="form-check-label" for="meal3">
            저녁
          </label>
        </div>
    </fieldset>
    <!-- 칼로리 선택 -->
    <div class="row mb-3 input-group mb-2">
      <label for="cal" class="col-sm-3 col-form-label">칼로리</label>
      <div class="col-sm-6">
          <select class="form-select ms-3" multiple aria-label="cal" name="cal" id="cal" required>
            <option value=4>200 ~ 300</option>
            <option value=1>300 ~ 400</option>
            <option value=2>400 ~ 500</option>
            <option value=3>500 ~ 600</option>
          </select>
      </div>  
      <div class="col-sm-2"> cal </div> 
    </div>
    <!-- 메뉴 -->
    <fieldset class="row mb-3 mb-2 input-group">
      <div class="col-sm-3 ms-3">
        <legend class="col-form-label row pt-0">구성</legend>
        <p class="row">복수선택O</p>
      </div>
      <div class = "col-sm-8">
        <div class="form-check  pb-2">
          <input class="form-check-input" type="checkbox" name="menu" id="menu1" value="ko">
          <label class="form-check-label" for="menu1">
            한식위주 - 밥or국
          </label>
        </div>
        <div class="form-check pb-2">
          <input class="form-check-input" type="checkbox" name="menu" id="menu2" value="western">
          <label class="form-check-label" for="menu2">
            양식
          </label>
        </div>
        <div class="form-check pb-2">
          <input class="form-check-input" type="checkbox" name="menu" id="menu3" value="salad">
          <label class="form-check-label" for="menu3">
            샐러드 종류
          </label>
        </div>
        <div class="form-check pb-2">
          <input class="form-check-input" type="checkbox" name="menu" id="menu4" value="sandwich">
          <label class="form-check-label" for="menu4">
            샌드위치 종류
          </label>
        </div>
        <div class="form-check pb-2">
          <input class="form-check-input" type="checkbox" name="menu" id="menu5" value="yogurt">
          <label class="form-check-label" for="menu5">
            요거트 종류
          </label>
        </div>
        <div class="form-check pb-2">
          <input class="form-check-input" type="checkbox" name="menu" id="menu6" value="protein">
          <label class="form-check-label" for="menu6">
            단백질
          </label>
        </div>
      </div>
    </fieldset>
    <!-- 제출 버튼-->
    <div class="container d-md-flex justify-content-md-center mb-3">
      <a href="" type="submit" class="btn btn-outline-primary">제출하기</a>
    </div>
    <hr>
    <!-- gpt 결과 -->
    <div class="container d-md-flex justify-content-md-center mb-3 ">
       <div class="mb-3">
        <label for="gpt" class="form-label">GPT 추천 식단 </label>
        <textarea class="form-control" id="gpt">
        1. 닭갈비 김치찌개 - 330kcal 2. 새우볶음밥 - 545kcal 3. 매생이볶음 - 225kcal 4. 북어국 - 385kcal 5. 잡채밥 - 410kcal
        </textarea>
      </div>
    </div>
  </div>
  
</div>

<!-- script 부분 -->
<!-- BMI 계산 처리 -->
<script>
  function calculateResult(event) {
    event.preventDefault(); // 폼 전송 취소

    // 사용자 입력값 가져오기
    const gender = document
      .getElementById('inputGender')
      .value;
    const age = Number(document.getElementById('inputAge').value);
    const height = Number(document.getElementById('inputHeight').value);
    const weight = Number(document.getElementById('inputWeight').value);

    // 계산 수행
    const bmi = weight / ((height / 100) ** 2);
    const minWeight = (18.5 * (height / 100) ** 2).toFixed();
    const maxWeight = (24.9 * (height / 100) ** 2).toFixed(1);

    // 검사 결과 계산
    let resultText;
    let resultColor;
    if (bmi < 18.5) {
      resultText = '저체중';
      resultColor = 'bg-success';
    } else if (bmi < 25) {
      resultText = '정상';
      resultColor = 'success bg-opacity-50';
    } else if (bmi < 30) {
      resultText = '과체중';
      resultColor = 'success bg-opacity-10';
    } else if (bmi < 35) {
      resultText = '비만';
      resultColor = 'warning-subtle';
    } else {
      resultText = '고도비만';
      resultColor = 'warning';
    }

    // 결과 표시
    const resultElem = document.getElementById('result');
    resultElem.textContent = bmi.toFixed(1);

    const resultTextElem = document.getElementById('resultText');
    resultTextElem.textContent = resultText;

    const resultRangeElem = document.getElementById('customRange1');
    resultRangeElem.value = bmi.toFixed(1);

    const resultContainerElem = document.getElementById('resultContainer');

    // 결과 보여주기


    // BMI 값 반환
    return bmi;
  }
</script>

<!-- 뒤로가기 -->
<script>
  function goBack() {
    window.history.back();
  }
</script>


{% endblock content%}