board/urls.py
from django.urls import path
from . import views

#게시판 API post
app_name = 'board'

urlpatterns = [
     #게시판
     path('', views.post_list, name='post_list'),                                  #게시판 전체 조회
     path('<int:category>', views.category_post_list, name='category_post_list'),  #게시판 카테고리 조회
     path('create_page/', views.create_page, name='create_page'),                  #게시글 작성 페이지 이동 
     path('post_detail/<int:post_id>', views.post_detail, name='post_detail'),     #게시글 상세 조회
     path('create/', views.post_create, name='post_create'),                       #게시글 작성
     path('delete/<int:post_id>', views.post_delete, name="post_delete"),          #게시글 삭제 
     path('update_page/<int:post_id>', views.update_page, name="update_page"),     #게시물 update 페이지 이동 
     path('update/<int:post_id>/', views.update, name='update'),                  #게시물 update

     #댓글 
     path('comment_create/<int:post_id>', views.comment_create, name="comment_create"),
     path('comment_delete/<int:comment_id>', views.comment_delete, name="comment_delete"),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views




app_name = "common"

urlpatterns = [
    path("", views.HomeView.as_view(), name="main"),
    path('login/', views.CustomLoginView.as_view(template_name="account/login.html"), name="login"),
    #path("login/", auth_views.LoginView.as_view(template_name="account/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.signup, name="signup")
]

# from .views import (
#     login_view,
#     logout_view,
#     signup_view,
# )

# app_name = 'account'
# urlpatterns = [
#     path('auth/', login_view, name='login'),
#     path('auth/expiration/', logout_view, name='logout'),
#     path('auth/new/', signup_view, name='signup'),
# ]

heco/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import BaseView, IndexView
from django.urls import path
from django.conf.urls import include
from heco import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path("", include("common.urls")),
    path('board/', include('board.urls')),
    path('chatbot/', include('gptChatBot.urls')),
    path('search/', include('search.urls')),
]

# urlpatterns = [
#     path("admin/", admin.site.urls),
#     path('base/', BaseView.as_view(), name='base'),
#     path('index/', IndexView.as_view(), name='index'),
#     path('board/', include('board.urls')),
#     path('account/', include('account.urls')),
# ]

templates/base.html
</html><!Doctype html>
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% block page_title %}
      <title>HECO</title>
    {% endblock page_title %}
  </head>

  <body>
    <!-- HTML 코드 -->
    <header>
      <nav class="navbar shadow-sm fixed-top bg-body-tertiary bg-light">
        <!-- Top navigaton - 앱 이름, 로그인, 회원가입 버튼 -->
        <div class="container-fluid">
          <a class="navbar-brand fs-3 ms-1 px-md-3 fw-bolder text-primary" href="{% url 'home' %}">HECO </a>
          {% if request.session.username %}
            <form class="d-flex justify-content-md-end">
              <a href="{% url 'common:logout' %}" class="fw-medium btn btn-outline-success me-2" type="button">로그아웃</a>
            </form>
          {% else %}
            <form class="d-flex justify-content-md-end">
              <a href="{% url 'common:login' %}" class="fw-medium btn btn-outline-success me-2" type="button">로그인</a>
              <a href="{% url 'common:signup' %}" class="fw-medium btn btn-outline-success me-2" type="button">회원가입</a>
            </form>
          {% endif %}
        </div>
        <!-- 페이지소개, 게시판(드롭다운 식단-운동), 헬스장 찾기 -->
        <div class="container-fluid justify-content-center">
          <ul class="nav nav-pills  fw-bold">
            <li class="nav-item">
              <a class="nav-link {% if request.path == '/' %}active{% endif %} px-5" aria-current="page" href="{% url 'home' %}">페이지 소개</a>
            </li>
            <li class="nav-item dropdown px-5">
              <a class="nav-link {% if 'board' in request.path %}active{% endif %} px-5" href="{% url 'board:post_list' %}">게시판</a>
            </li>
            <li class="nav-item px-5">
              <a class="nav-link" href="#">헬스장 찾기</a>
            </li>
          </ul>
        </div>
        {% block navbar %}
        {% endblock navbar%}
      </nav>
    </header>

    {% block content %}{% endblock content%}
    
    <footer class="bd-footer shadow-sm  py-1 py-md-1 mt-5 bg-body-tertiary">
      <div class="container py-1 py-md-1 px-4 px-md-3 text-body-secondary">
        <div class="row pt-5">
          <div class="col-lg-3 mb-3">
            <a class="d-inline-flex align-items-center mb-2 text-body-emphasis text-decoration-none" href="#">
              <title>HECO - Healthy</title>
              <span class="fs-5">HECO - Healthy Community</span>
            </a>
            <ul class="list-unstyled small">
              <li class="mb-2">MC Cloud Major Project - Team2</li>
              <li class="mb-2">Changmin, Sunghyun, Jinhwan, Taeeun</li>
              <li class="mb-2">Github</li>
              <li class="mb-2">Currently 2023</li>
            </ul>
          </div>
          <div class="col-4 col-lg-4 offset-lg-1 mb-3">
            <h5>Links </h5>
            <ul class="list-unstyled">
              <li class="mb-2">
                <a class="link-underline-opacity-0 link-dark text-body-secondary" href="/">Home</a>
                <a class="link-underline-opacity-0 link-dark text-body-secondary" href="/" disabled>/</a>
                <a class="link-underline-opacity-0 link-dark text-body-secondary" href="/">헬스장 찾기</a>
              </li>
              <li class="mb-2 ">
                <a class="link-underline-opacity-0 link-dark text-body-secondary" href="{% url 'board:category_post_list' 1 %}?id={{ id }}&username={{ username }}">식단 게시판</a>
                <a class="link-underline-opacity-0 link-dark text-body-secondary" href="/" disabled>/</a>
                <a class="link-underline-opacity-0 link-dark text-body-secondary" href="{% url 'board:category_post_list' 2 %}?id={{ id }}&username={{ username }}">운동 게시판</a>
              </li>
              <li class="mb-2">
                <a class="link-underline-opacity-0 link-dark text-body-secondary" href="{% url 'board:post_list' %}">BMI 계산</a>
                <a class="link-underline-opacity-0 link-dark text-body-secondary" href="/" disabled>/</a>
                <a class="link-underline-opacity-0 link-dark text-body-secondary" href="{% url 'board:post_list' %}">식단 추천</a>
              </li>
            </ul>
          </div>
          <div class="col-4 col-lg-4 mb-3">
            <h5>Youtube</h5>
            <ul class="list-unstyled">
              <li class="mb-2">
                <a class="link-underline-opacity-0 link-dark text-body-secondary" href="https://www.youtube.com/@GYMJONGKOOK"target="_blank"rel="noopener">짐종국</a> 
                <a class="link-underline-opacity-0 link-dark text-body-secondary" href="/" disabled>/</a>
                <a class="link-underline-opacity-0 link-dark text-body-secondary" href="https://www.youtube.com/@physicalgallery_official">피지컬갤러리</a>
              </li>
              <li class="mb-2">
                <a class="link-underline-opacity-0 link-dark text-body-secondary" href="https://www.youtube.com/@euddeume">힙으뜸</a>
                <a class="link-underline-opacity-0 link-dark text-body-secondary" href="/" disabled>/</a>
                <a class="link-underline-opacity-0 link-dark text-body-secondary" href="https://www.youtube.com/@AllblancTV">Allbalanc TV</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

    <!-- js 리소스 -->
    
    <script src="https://unpkg.com/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    

  </body>

</html>

templates/form_error.html
{% if form.errors %}

  <div>
    {% for field in form %}

      {% if field.errors %}
        <div>
          <strong>{{field.label}}</strong>
          {{field.errors}}
        </div>
      {% endif %}

    {% endfor %}

    {% for error in form.non_field_errors %}
      <div>
        <strong>{{error}}</strong>
      </div>
    {% endfor %}
  </div>

{% endif %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block page_title %}
  <title>HECO</title>
{% endblock page_title %}

{% block content %}
<br>
  <!-- 1단락 -->
<div class="container mx-auto mt-5 pt-1 mb-5"  >
  <div class="row mt-3 pt-5 mb-5 ">
    <div class="py-5 col-lg-6 pt-4 order-2 order-lg-1 flex-column" >
      <br><br><br>
      <p style="font-size: 45px;" class="fw-bold">건강한 몸은 <br>
      <p style="font-size: 45px;" class="fw-bold d-flex justify-content-md-end"> HECO에서 시작됩니다.</p>
      </p>
      <h4 class="lh-base mb-5 d-flex "><hr>
        건강한 몸을 가지고 싶으신가요?  지금 바로 HECO와 함께 운동과 식단에 대해 알아볼 수 있습니다.<br>
      </h4>
      <div class="d-flex justify-content-md-center ">
        <a class="btn btn-primary col-sm-7 shadow-sm" href="{% url 'common:signup' %}">지금 시작하세요</a>
      </div>
    </div>
    <div class="col-lg-6 shadow pt-4 order-1 order-lg-2 py-9">
      <img src="{% static 'images/index_03.jpg' %}" class="img-fluid" alt=""><br>
    </div>
  </div>
  <br>
</div>

<!-- 2단락 시작 -->
<div class="container">
  <div class="row mb-5">
    <h3 class="text-center fw-bold pb-2"> 게시판 안내 </h4><hr><br>
    <div class="col-xl-6 col-lg-6 shadow d-flex justify-content-center align-items-stretch position-relative">
      <img src="{% static 'images/index_01.jpg' %}" class="img-fluid " alt="">
    </div>
    <div class="col-xl-6 col-lg-5 d-flex flex-column align-items-stretch justify-content-center py-5 px-lg-5">
      <a class="link-dark "href="{% url 'board:category_post_list' 1 %}?id={{ id }}&username={{ username }}">
        <h4>식단 게시판</h4>
      </a>
      <p class="fs-5">
        잘먹은게 중요합니다. 사람들과 식단을 공유하며 어떤것을 어떻게 먹어야하는지 알 수 있습니다. </p>
      <p class="fs-6 fw-bold">#식단#기록#해독주스#단백질#쉐이크#삼시세끼#닭가슴살#멈춰</p>
      <br><br>
      <a class="link-dark " href="{% url 'board:category_post_list' 2%}?id={{ id }}&username={{ username }}">
        <h4>운동 게시판</h4>
      </a>
      <p class="fs-5"> 사람들의 노하우가 담겨있는 운동일일지를 공유하며 나에게 알맞는 운동을 알 수 있습니다.</p>
      <p class="fs-6 fw-bold">#오운완#인증#헬스#헬린이#헬창#3대500#같이#운동해요</p>
    </div>
  </div>
</div>
<br>
<!-- 3단락 -->
<div class="container">
  <div class="row mt-2 mb-5">
    <h3 class="text-center fw-bold pb-2"> 지원 서비스</h4><hr>
    <div class="col-sm-4 mb-5 mt-3">
      <div class="card  shadow">
        <h4 class="card-title text-center fw-medium mb-2 mt-3">체지방 측정</h4>
        <div class="card-body">
          <img src="{% static 'images/index_bmi.jpg' %}" class="card-img-top mb-2" alt="...">
          <p class="card-tex fs-5">신체정보로 측정 받아보세요 적절한 식단과 운동을 계획하는데 도움이 됩니다.</p>
          <a href="{% url 'board:post_list' %}" class="btn btn-primary">BMI 계산기</a>
        </div>
      </div>
    </div>
    <div class="col-sm-4 mb-5 mt-3">
      <div class="card shadow">
        <h4 class="card-title text-center fw-medium mb-2 mt-3">GPT 챗봇한테 식단추천 받기</h4>
        <div class="card-body">
          <img src="{% static 'images/index_diet.jpg' %}" class="card-img-top mb-2" alt="...">
          <p class="card-text fs-5">식사 시간, 음식 종류, 칼로리 등을 선택하여 GPT에게 식단추천을 받아보세요.</p>
          <a href="{% url 'board:post_list' %}" class="btn btn-primary">식단추천 받기</a>
        </div>
      </div>
    </div>
    <div class="col-sm-4 mb-5 mt-3">
      <div class="card shadow">
        <h4 class="card-title text-center fw-medium mb-2 mt-3">헬스장 찾기</h4>
        <div class="card-body">
          <img src="{% static 'images/index_gym.jpg' %}" class="card-img-top mb-2" alt="...">
          <p class="card-text fs-5">kakao map api를 통해 나의 위치를 기반으로한 근처 헬스장을 찾아보세요.</p>
          <a href="/" class="btn btn-primary">근처 헬스장 찾기</a>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- 4단락 -->
<div class="container">
  <div class="row g-4 mt-2 mb-5 d-flex justify-content-md-center">
    <p style="font-size: 30px;" class="lh-lg shadow-sm fw-medium text-center"> 
      매일 사용자들은 HECO를 통해 목표를 달성합니다. <br>
      미래를 향한 여정에 동참해 보세요.<br>
      HECO의 많은 사람들은 여러분이 식단과 운동을 공유하기를 기다리고 있습니다.<br>
      <br>
    </p>
    <div class="row mt-5 mb-5 flex justify-content-md-center ">
      <a class="btn btn-outline-white col-sm-4 shadow-sm me-2 fw-bolder fs-3" href="{% url 'common:signup' %}">HECO</a>
    </div>
  </div>      
</div>
{% endblock %}